name: flutter_q
description: Q project
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  abstract_bloc: ^0.4.3
  rest_api_client: ^2.1.2
  storage_repository: ^1.1.9
  gap: ^2.0.0
  get_it: ^7.2.0
  intl: ^0.17.0
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  octo_image: ^1.0.2
  cached_network_image: ^3.2.1
  connectivity_plus: ^2.3.6
  hive: ^2.2.3
  hive_generator: ^1.1.3
  flutter_riverpod: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  flutter_lints: ^2.0.1
  freezed: ^2.1.0+1

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/icons/fonts/AppIcons.ttf

  assets:
    - assets/images/