name: flutter_q
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

flutter_intl:
  main_locale: en
  enabled: true

dependencies:
  beamer: ^1.5.3
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.1.0
  hooks_riverpod: ^2.0.2
  intl: ^0.17.0
  retrofit: ^3.0.2
  sentry_flutter: ^6.11.2
  pull_to_refresh: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.3
  cached_network_image: ^3.2.1
  octo_image: ^1.0.2
  gap: ^2.0.0

dev_dependencies:
  build_runner: ^2.2.1
  dart_code_metrics: ^4.19.1
  flutter_flavorizr: ^2.1.4
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.4.1
  mockito: ^5.3.2
  pretty_dio_logger: ^1.1.1
  retrofit_generator: null

flutter:
  uses-material-design: true
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/icons/fonts/AppIcons.ttf

  assets:
    - assets/images/

